### ISSUE TITLE
Cannot compile qng

### ISSUE THREAD

**Issue by condor666** [SleuthKid/netglub#1]
OS used : Kali 2.0 64 bits
Dependencies installed without problem.
Master and Slave compiled successfully, on qng i've that error : 

```
src/filemanager.cpp: In member function 'QString FileManager::createTmpDirFromNtg(Graph*, QString)':
src/filemanager.cpp:218:20: error: could not convert 'false' from 'bool' to 'QString' return false;
```

@SleuthKid please can you check it ?

**Comment by psychomad** [comment]
Same issue
No problem with master and slave

**Comment by SleuthKid** [comment]
I will have a look and see if I can find a qickfix.
